stages:
  - package
  - deploy

package:
  image: debian:stretch
  stage: package
  before_script:
    - apt-get update
    - apt-get install -y python3-pip python3-simplejson python3-setuptools ruby ruby-dev rubygems build-essential git
    - gem install --no-ri --no-rdoc fpm
    - pip3 install virtualenv virtualenv-tools -y
  script:
    - fpm --verbose -s virtualenv --python-pip /usr/bin/pip3 --setup-install ./setup.py --python-bin /usr/bin/python3 -t deb -a all --deb-systemd "prometheus-junos-exporter.service" requirements.txt
  artifacts:
    paths:
      - "*.deb"
  allow_failure: false

release_package:
  image: debian:stretch
  stage: deploy
  dependencies:
    - package
  before_script:
    - dpkg -c prometheus-junos-exporter*.deb
    - apt-get update
    - apt-get install -y python3-requests wget
    - wget https://$PACKAGE_FACTORY/aptly.py
  script:
    - export FILENAME=$(ls prometheus-*-exporter*.deb)
    - python3 aptly.py -a https://$PACKAGE_FACTORY/api -f $CI_PROJECT_NAME -r selfnet-prometheus -u $APTLYUSER -p $APTLYPASSWORD -g $SIGN_PASSPHRASE $FILENAME
  only:
    - master
  allow_failure: false

