stages:
  - package
  - deploy

package:
  image: debian:stretch
  stage: package
  before_script:
    - apt-get update
    - apt-get install -y python3-pip python3-virtualenv ruby ruby-dev rubygems build-essential
    - gem install --no-ri --no-rdoc fpm
  script:
    - fpm --verbose -s virtualenv -t deb -a all --python-virtualenv /usr/bin/virtualenv3 --python-pip /usr/bin/pip3 --python-bin /usr/bin/python3 --deb-systemd "prometheus-junos-exporter.service" ./setup.py
  artifacts:
    paths:
      - "*.deb"
  allow_failure: false

release_package:
  image: debian:stretch
  stage: deploy
  dependencies:
    - package
  before_script:
    - dpkg -c prometheus-junos-exporter*.deb
    - apt-get update
    - apt-get install -y python3-requests wget
    - wget https://$PACKAGE_FACTORY/aptly.py
  script:
    - export FILENAME=$(ls prometheus-*-exporter*.deb)
    - python3 aptly.py -a https://$PACKAGE_FACTORY/api -f $CI_PROJECT_NAME -r selfnet-prometheus -u $APTLYUSER -p $APTLYPASSWORD -g $SIGN_PASSPHRASE $FILENAME
  only:
    - master
  allow_failure: false

