- job_name: get_switch_metrics
  scrape_interval: 300s
  scrape_timeout: 120s

  scheme: http

  metrics_path: /metrics

  file_sd_configs:

    - files:  [ sd_configs.json ]

  relabel_configs:

    - source_labels: [__address__]

      regex: (.*)(:9332)?

      target_label: __param_target

      replacement: ${1}

    - source_labels: [__param_target]

      regex: (.*)

      target_label: instance

      replacement: ${1}

    - source_labels: []

      regex: .*

      target_label: __address__

      replacement: exporter.example

