---
METRICS:
  Counter:
    - metric: prefixes_received
      type: total
      key: pfx_rx
      description: Received Prefixes from Peer
      function: none_to_zero

    - metric: prefixes_received_accepted
      type: total
      key: pfx_rx_accepted
      description: Accepted Prefixes from Peer
      function: none_to_zero

    - metric: prefixes_sent
      type: total
      key: pfx_tx
      description: Sent Prefixes to Peer
      function: none_to_zero

  Gauge:
    - metric: is_up
      type: status
      key: peerstate
      description: BGP Session is established (0(DOWN)/1(UP))
      function: is_ok

LABELS:
  - label: peername
    key: peername

  - label: peeraddress
    key: peeraddr