---
METRICS:
  Counter:
    - metric: prefixes_received
      type: total
      key: pfx_rx
      description: Received Prefixes from Peer
      function: none_to_zero
  
  Gauge:
    - metric: is_up
      type: status
      key: peerstate
      description: BGP Session is established (0(DOWN)/1(UP))
      function: is_ok

LABELS:
  - label: peername
    key: peername

  - label: peeraddress
    key: peeraddr