---
DEFINITIONS:
  NETWORK_METRICS:
    Gauge:
      - metrik: last_flapped
        key: flapped
        type: seconds
        description: Port Date (Unix TimeStamp) for last flap
        function: flap

      - metrik: is_up
        key: running
        description: Port is_up (0(DOWN)/1(UP))
        function: is_ok

      - metrik: is_operational
        key: oper
        description: Port oper (0(DOWN)/1(UP))
        function: is_ok

      - metrik: is_admin
        key: admin
        description: Port admin (0(DOWN)/1(UP))
        function: is_ok

      - metrik: is_enabled
        key: present
        description: Port is_enabled (0(DOWN)/1(UP))
        function: is_ok

    # Optic Specific
      - metrik: temperature
        key: module_temperature
        type: celsius
        description: Port SFP temperature
        function: temp

      - metrik: sending_optic_power
        key: tx_optic_power
        description: Sending Power on interface
        type: amperes
        function: floatify
  
      - metrik: receiving_optic_power
        key: rx_optic_power
        description: Receiving Power on interface
        type: amperes
        function: floatify

      - metrik: voltage
        key: module_voltage
        description: Port SFP voltage
        type: amperes
        function: floatify

    Counter:
      - metrik: received
        key: rx_bytes
        description: Total received Bytes by Port
        type: bytes_total
        function: intify

      - metrik: transmitted
        key: tx_bytes
        description: Total transmitted Bytes of Port
        type: bytes_total
        function: intify

      - metrik: receive_drops
        type: total
        key: rx_err_drops
        description: Received Packets dropped
        function: intify
      
      - metrik: transmit_drops
        type: total
        key: tx_err_drops
        description: transmitted packets 
        function: intify

      - metrik: receive_error_frames
        type: total
        key: rx_err_frame
        description: received messed up packets
        function: intify

      - metrik: receive_error_layer2_channel
        type: total
        key: rx_err_l2-channel
        description: receive errored layer2 packets
        function: intify

      - metrik: receive_error_layer3_incompletes
        type: total
        key: rx_err_l3-incompletes
        description: incomplete layer3 packets
        function: intify

      - metrik: receive_error_layer2_mismatch
        type: total
        key: rx_err_l2-mismatch
        description: mismatched layer2 packets
        function: intify

      - metrik: receive_error_fifo
        type: total
        key: rx_err_fifo
        description: FIFO errors receiving
        function: intify

      - metrik: receive_error_ressource
        type: total
        key: rx_err_resource
        description: Wrong ressources receive errors
        function: intify

      - metrik: transmit_error_carrier_transitions
        type: total
        key: tx_err_carrier-transitions
        description: Transmitted error carrier transitions
        function: intify

      - metrik: transmit_error_output
        type: total
        key: tx_err_output
        description: Transmitted errors on packets output
        function: intify

      - metrik: transmit_error_collisions
        type: total
        key: tx_err_collisions
        description: Transmitted collisions
        function: intify

      - metrik: transmit_error_drops
        type: total
        key: tx_err_drops
        description: Transmit errors on drop
        function: intify

      - metrik: transmit_error_aged
        type: total
        key: tx_err_aged
        description: transmit error on aged packets
        function: intify

      - metrik: transmit_error_mtu
        type: total
        key: tx_err_mtu
        description: transmit error due to wrong mtu
        function: intify

      - metrik: transmit_error_fifo
        type: total
        key: tx_err_fifo
        description: FIFO errors 
        function: intify

      - metrik: transmit_error_ressource
        type: total
        key: tx_err_resource
        description: error on wrong ressource
        function: intify

  NETWORK_LABEL_WRAPPER:
    - label: description
      key: description

    - label: MAC
      key: macaddr

    - label: speed
      key: speed
  ENVIRONMENT_METRICS:
    Gauge:
      - metrik: uptime
        key: uptime
        description: Uptime of the Host.
        type: seconds_total
        function: intify

      - metrik: fan
        type: status
        key: Fans
        description: Fan STATUS (0(WRACKED)/1(OK))
        function: fan_power_temp_status
        specific: yes
      
      - metrik: power
        type: status
        key: Power
        description: Power STATUS (0(WRACKED)/1(OK))
        function: fan_power_temp_status
        specific: yes
  
      - metrik: temp
        type: status
        key: Temp
        description: Temperature Sensor STATUS (0(WRACKED)/1(OK))
        function: fan_power_temp_status
        specific: yes

      - metrik: temp
        type: celsius
        key: Temp
        description: Temperature Sensor Value in celsius
        function: temp_celsius
        specific: yes

      - metrik: reboot
        type: status
        key: RE0
        description: Last Reboot REASON (0(WRACKED)/1(OK))
        function: reboot
        specific: yes
      
      - metrik: cpu_usage
        type: ratio
        key: re_loads
        description: Current CPU Load Ratio in percent
        function: cpu_usage
        specific: yes
      
      - metrik: cpu_idle
        type: ratio
        key: re_loads
        description: Current CPU Idle Ratio in percent
        function: cpu_idle
        specific: yes

      - metrik: ram_usage
        type: bytes_total
        key: re_loads
        description: Current Memory Usage in bytes
        function: ram_usage
        specific: yes

      - metrik: ram
        type: bytes_total
        key: re_loads
        description: Available Memory in bytes
        function: ram
        specific: yes

  ENVIRONMENT_LABEL_WRAPPER:

    - label: software_version
      key: version
  
    - label: hardware_model
      key: model

    - label: personality
      key: personality