---

DEFINITIONS:
  METRICS_BASE:
    base: ubiquity_airmax
    interface: interface
    device: device
    wireless: wireless
  NETWORK_METRICS:
    Counter:
      - metric: tx
        key: tx_bytes
        type: bytes_total
        description: Total number of transmitted bytes
      - metric: rx
        key: rx_bytes
        type: bytes_total
        description: Total number of received bytes
      - metric: tx_errors
        key: tx_errors
        type: total
        description: Total transmition errors
      - metric: rx_errors
        key: rx_errors
        type: total
        description: Total received errors
    Gauge:
      - metric: is_up
        key: plugged
        type: status
        description: Status of interface (0 DOWN/1 UP)
        function: is_ok
      - metric: cable_length
        key: cable_len
        type: meters
        description: Cable length to the Port
  NETWORK_LABEL_WRAPPER:
    - label: speed
      key: speed

  ENVIRONMENT_METRICS:
    Gauge:
      - metric: uptime
        key: uptime
        description: Uptime of the host.
        type: seconds
      - metric: ram
        key: totalram
        type: bytes_total
        description: Total ram in bytes.
      - metric: ram
        type: bytes_free
        key: freeram
        description: Free ram in bytes
      - metric: cpu_load
        type: percent
        key: cpuload
        description: CPU Load in percent.
