RoutingEngineTable:
  rpc: get-route-engine-information
  args:
  item: route-engine
  key: slot | model
  view: RoutingEngineView

RoutingEngineView:
  fields:
    model: model
    last_reboot_reason: last-reboot-reason
    uptime: { up-time/@seconds: int }
    cpu_idle: { cpu-idle: int }
    memory_dram_size: memory-dram-size
    memory_buffer_utilization : { memory-buffer-utilization: int }

SoftwareTable:
  rpc: get-software-information
  args:
  item: multi-routing-engine-item
  key: re-name
  view: SoftwareView

SoftwareView:
  fields:
    hostname: software-information/host-name
    model: software-information/product-model
    version: software-information/junos-version


EnvironmentTable:
  rpc: get-environment-information
  args:
  item: environment-item
  key: name
  view: EnvironmentView

EnvironmentView:
  fields:
    class: class
    status: status
    temperature: { temperature/@celsius: int }