---

DEFINITIONS:
  METRICS_BASE:
    base: ubiquity_airmax
    interface: interface
    device: device
    wireless: wireless
  NETWORK_METRICS:
    Counter:
      - metric: transmitted
        key: tx_bytes
        type: bytes_total
        description: Total number of transmitted bytes
      - metric: received
        key: rx_bytes
        type: bytes_total
        description: Total number of received bytes
      - metric: transmit_errors
        key: tx_errors
        type: total
        description: Total transmition errors
      - metric: receive_errors
        key: rx_errors
        type: total
        description: Total received errors
    Gauge:
      - metric: is_up
        key: plugged
        type: status
        description: Status of interface (0 DOWN/1 UP)
        function: is_ok
      - metric: cable_length
        key: cable_len
        type: meters
        description: Cable length to the Port
  NETWORK_LABEL_WRAPPER:
    - label: speed
      key: speed

  ENVIRONMENT_METRICS:
    Gauge:
      - metric: uptime
        key: uptime
        description: Uptime of the host.
        type: seconds
      - metric: ram
        key: totalram
        type: bytes
        description: Total ram in bytes.
      - metric: ram
        type: bytes_free
        key: freeram
        description: Free ram in bytes
      - metric: cpu_load
        type: percent
        key: cpuload
        description: CPU Load in percent.

  WIRELESS_METRICS:
    Gauge:
      - metric: band
        type: type
        key: band
        description: Band Type of the Radio used (2 5GHz (11acvht), 1 2.4GHz (11nght))
      - metric: antenna_gain
        type: decibel
        key: antenna_gain
        description: Antenna gain in decibel
      - metric: frequency
        type: mhz
        key: frequency
        description: The base frequency.
      - metric: frequency_center1
        type: mhz
        key: center1_freq
        description: Center 1 frequency of the device
      - metric: distance
        type: meters
        key: distance
        description: Distance between remote and local station
      - metric: transmitting_power
        type: dbm
        key: txpower
        description: TX Power of the station
      - metric: channel_bandwith
        type: percent
        key: chanbw
        description: Channel bandwith in percent 0-100%

  POLLING_METRICS:
    Gauge:
      - metric: receiving_capacity
        key: dcap
        type: kilobytes
        description: The available capacity for receiving packets
      - metric: transmitting_capacity
        key: ucap
        type: kilobytes
        description: The available capacity for transmitting packets
      - metric: receiving_capacity_used
        key: receiving_airtime
        type: percent
        description: Airtime inbound in percent 10 times
      - metric: transmitting_airtime
        key: tx_use
        type: percent
        description: Airtime outbound in percent 10 times
      - metric: airtime
        key: use
        type: percent
        description: The Airtime 10 times 
  
  STATS_METRICS:
    Counter:
      - metric: received
        type: bytes_total
        key: rx_bytes
        description: Received bytes total on the wireless link.
      - metric: transmitted
        type: bytes_total
        key: tx_bytes
        description: Transmitted bytes total on the wireless link.

  STATION_METRICS:
    Gauge:
      - metric: transmition_latency
        key: tx_latency
        type: milliseconds
        description: The transmition latency between the stations
      - metric: receiving_power
        key: signal
        type: dbm
        description: The power of the received signal
      - metric:  received_signal_strength_indication
        key: tx_latency
        type: indication
        description: The rssi value of the remote bridge
      - metric: noise_floor
        type: dbm
        key: noisefloor
        description: The noise floor in dbm
  AIRMAX_METRICS:
    Gauge:
      - metric: transmition
        key: tx_cinr
        type: cinr
        description: TX CINR Value of AP
      - metric: receiving
        key: rx_cinr
        type: cinr
        description: RX CINR Value of AP
      - metric: transmition_usage
        key: tx_usage
        type: percent
        description: TX Usage Value of AP 10 times
      - metric: receiving_usage
        key: rx_usage
        type: percent
        description: RX Usage Value of AP 10 times